### ISSUE TITLE
Human-to-SQL Query Generation with Charting

### ISSUE THREAD

**Issue by numberonewastefellow** [onyx-dot-app/onyx#1566]
I am requesting the implementation of a feature that allows users to input natural language questions, which are then converted into SQL queries by an LLM. The generated query should be executed on the database to fetch records (up to 10 by default, configurable). If the user's question includes a request for a chart, the results should be plotted using Plotly or another suitable library.

A bounty will be offered for this feature, and a pull request will be created upon approval.

**Comment by aropenai** [comment]
Nice feature. Expecting soon

**Comment by TechGeniusBlogger** [comment]
Anyone open for this? I am interested too
