### ISSUE TITLE
Is it intended that the metadata only work with .txt files and not with e.g. PDFs?

### ISSUE THREAD

**Issue by silberda** [onyx-dot-app/onyx#2477]
I always understood the [documentation ](https://docs.danswer.dev/connectors/file) of the file connector like it's supposed to handle metadata in all of the supported data formats. But apparently I can only get it to work with .txt files. Is that intended and misinterpreted by me or a bug?

**Comment by pablodanswer** [comment]
Which file formats have you tried that haven't worked? Danswer should be able to pick up PDF metadata e.g.
