### ISSUE TITLE
After renaming to onyx, helm charts are now broken

### ISSUE THREAD

**Issue by ar-or** [onyx-dot-app/onyx#3376]
In `https://github.com/onyx-dot-app/onyx/blob/main/deployment/helm/charts/danswer/Chart.yaml`

` repository: https://danswer-ai.github.io/vespa-helm-charts`   is no longer accessible.

**Comment by rkuo-danswer** [comment]
Will fix with https://github.com/onyx-dot-app/onyx/pull/3412
